// AUTOGENERATED FILE
// This file was generated from methodScript.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface MethodScriptActionDict<T> extends BaseActionDict<T> {
  Program?: (this: NonterminalNode, arg0: IterationNode) => T;
  Action?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: IterationNode) => T;
  ActionType?: (this: NonterminalNode, arg0: TerminalNode) => T;
  ActionDegree?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  StateIdentifier?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PlayerStuff?: (this: NonterminalNode, arg0: TerminalNode) => T;
  Identifier?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  name?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  Keyword?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Value?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  StringLiteral?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  NumberLiteral?: (this: NonterminalNode, arg0: IterationNode) => T;
  BooleanLiteral?: (this: NonterminalNode, arg0: TerminalNode) => T;
  space?: (this: NonterminalNode, arg0: TerminalNode) => T;
}

export interface MethodScriptSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: MethodScriptActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: MethodScriptActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: MethodScriptActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: MethodScriptActionDict<T>): this;
}

export interface MethodScriptGrammar extends Grammar {
  createSemantics(): MethodScriptSemantics;
  extendSemantics(superSemantics: MethodScriptSemantics): MethodScriptSemantics;
}

declare const grammar: MethodScriptGrammar;
export default grammar;

