// AUTOGENERATED FILE
// This file was generated from respondscript.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface RespondScriptActionDict<T> extends BaseActionDict<T> {
  Program?: (this: NonterminalNode, arg0: IterationNode, arg1: NonterminalNode, arg2: IterationNode) => T;
  Default?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Statement?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  StateDeclaration?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: NonterminalNode, arg4: TerminalNode) => T;
  MethodDeclaration?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: IterationNode, arg3: IterationNode, arg4: IterationNode, arg5: TerminalNode) => T;
  ConditionalBlock?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: IterationNode, arg3: TerminalNode) => T;
  IfClause?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: IterationNode) => T;
  ElseIfClause?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: IterationNode) => T;
  ElseClause?: (this: NonterminalNode, arg0: TerminalNode, arg1: TerminalNode, arg2: IterationNode) => T;
  Condition?: (this: NonterminalNode, arg0: NonterminalNode, arg1: NonterminalNode, arg2: NonterminalNode) => T;
  Comparator?: (this: NonterminalNode, arg0: TerminalNode) => T;
  EmbedState?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  IdentifierOperation?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode, arg2: IterationNode) => T;
  RightHandSide?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Operand?: (this: NonterminalNode, arg0: TerminalNode) => T;
  RollDeclaration?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode, arg3: IterationNode, arg4: TerminalNode, arg5: IterationNode, arg6: TerminalNode, arg7: NonterminalNode, arg8: IterationNode, arg9: TerminalNode) => T;
  RollSucceed?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
  RollFail?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode) => T;
  Approach?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Skill?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  Display?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  PlainText?: (this: NonterminalNode, arg0: IterationNode) => T;
  Identifier?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  name?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  Keyword?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
  Value?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  StringLiteral?: (this: NonterminalNode, arg0: IterationNode) => T;
  NumberLiteral?: (this: NonterminalNode, arg0: IterationNode) => T;
  BooleanLiteral?: (this: NonterminalNode, arg0: TerminalNode) => T;
  ActionType?: (this: NonterminalNode, arg0: TerminalNode) => T;
  ActionDegree?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  QuotedString?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  space?: (this: NonterminalNode, arg0: TerminalNode) => T;
}

export interface RespondScriptSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: RespondScriptActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: RespondScriptActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: RespondScriptActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: RespondScriptActionDict<T>): this;
}

export interface RespondScriptGrammar extends Grammar {
  createSemantics(): RespondScriptSemantics;
  extendSemantics(superSemantics: RespondScriptSemantics): RespondScriptSemantics;
}

declare const grammar: RespondScriptGrammar;
export default grammar;

