// AUTOGENERATED FILE
// This file was generated from stateDeclaration.ohm by `ohm generateBundles`.

import {
  BaseActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface StateScriptActionDict<T> extends BaseActionDict<T> {
  StateList?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  IndividualState?: (this: NonterminalNode, arg0: NonterminalNode, arg1: TerminalNode, arg2: NonterminalNode) => T;
  Identifier?: (this: NonterminalNode, arg0: IterationNode) => T;
  Value?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  StringLiteral?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  NumberLiteral?: (this: NonterminalNode, arg0: IterationNode) => T;
  BooleanLiteral?: (this: NonterminalNode, arg0: TerminalNode) => T;
}

export interface StateScriptSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: StateScriptActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: StateScriptActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: StateScriptActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: StateScriptActionDict<T>): this;
}

export interface StateScriptGrammar extends Grammar {
  createSemantics(): StateScriptSemantics;
  extendSemantics(superSemantics: StateScriptSemantics): StateScriptSemantics;
}

declare const grammar: StateScriptGrammar;
export default grammar;

